# Generated by Django 4.2.5 on 2023-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=10),
        ),
    ]
